import { expect, test } from '@playwright/test'

test.setTimeout(120_000)

const barcode = '6800000000777'
const skuCode = 'FULL-E2E-01'
const productName = '全流程验收篮球'

test('从扫码入库到销售退货、盘点、报表和备份的完整业务链路', async ({ page }) => {
  await page.goto('/catalog')
  const categories = page.locator('section[aria-labelledby="categories-title"]')
  const majorForm = categories.locator('form').nth(0)
  await majorForm.getByLabel('两位编号').fill('68')
  await majorForm.getByLabel('大类名称').fill('全流程球类')
  await majorForm.getByRole('button', { name: '新增大类' }).click()
  const minorForm = categories.locator('form').nth(1)
  await minorForm.getByLabel('所属大类').selectOption({ label: '68 全流程球类' })
  await minorForm.getByLabel('两位编号').fill('01')
  await minorForm.getByLabel('小类名称').fill('全流程篮球')
  await minorForm.getByRole('button', { name: '新增小类' }).click()
  const brands = page.locator('section[aria-labelledby="brands-title"]')
  await brands.getByLabel('品牌名称').first().fill('全流程验收品牌')
  await brands.getByRole('button', { name: '新增品牌' }).click()
  await expect(brands.getByLabel('品牌名称')).toHaveCount(2)
  await expect(brands.getByLabel('品牌名称').nth(1)).toHaveValue('全流程验收品牌')

  await page.goto('/inbounds')
  await page.getByTestId('barcode-input').fill(barcode)
  await page.getByTestId('scan-submit').click()
  const create = page.getByTestId('quick-create-dialog')
  await create.getByTestId('quick-sub-category').selectOption({ label: '01 全流程篮球' })
  await create.getByTestId('quick-product-name').fill(productName)
  await create.getByLabel('品牌').selectOption({ label: '全流程验收品牌' })
  await create.getByTestId('quick-sku-code').fill(skuCode)
  await create.getByTestId('quick-retail-price').fill('180')
  await create.getByTestId('quick-save').click()
  await page.getByTestId('pending-quantity').fill('10')
  await page.getByTestId('pending-unit-cost').fill('100')
  await page.getByTestId('add-line').click()
  await page.getByTestId('confirm-inbound').click()
  await expect(page.getByRole('status')).toContainText('入库成功')

  await page.goto('/inbounds')
  await page.getByTestId('barcode-input').fill(barcode)
  await page.getByTestId('scan-submit').click()
  await page.getByTestId('pending-quantity').fill('10')
  await page.getByTestId('pending-unit-cost').fill('120')
  await page.getByTestId('add-line').click()
  await page.getByTestId('confirm-inbound').click()
  await expect(page.getByRole('status')).toContainText('入库成功')

  await page.goto('/inventory')
  let inventoryRow = page.getByRole('row').filter({ hasText: barcode })
  await expect(inventoryRow.locator('td').nth(6)).toHaveText('20')
  await expect(inventoryRow.locator('td').nth(7)).toHaveText('110.0000')

  await page.goto('/sales')
  await page.getByTestId('barcode-input').fill(barcode)
  await page.getByTestId('scan-submit').click()
  const saleQuantity = page.getByTestId('checkout-cart').locator('input[type="number"]')
  await expect(saleQuantity).toHaveValue('1')
  await page.getByTestId('barcode-input').fill(barcode)
  await page.getByTestId('scan-submit').click()
  await expect(saleQuantity).toHaveValue('2')
  await page.getByTestId('open-payment').click()
  await expect(page.getByTestId('payment-amount')).toHaveValue('360.00')
  await page.getByTestId('confirm-payment').click()
  const receipt = page.getByRole('dialog').filter({ hasText: '销售小票' })
  const saleNo = (await receipt.locator('dd').first().innerText()).trim()
  await receipt.getByRole('button', { name: '关闭' }).click()

  await page.goto('/sales/history')
  await page.getByRole('row').filter({ hasText: saleNo }).getByRole('link', { name: '查看详情' }).click()
  await page.getByRole('button', { name: '原单退货' }).click()
  const returnDialog = page.getByRole('dialog').filter({ hasText: '原单退货' })
  await returnDialog.getByTestId(/return-quantity-/).fill('1')
  await expect(returnDialog.getByTestId('refund-preview')).toContainText('180.00')
  await returnDialog.getByTestId('confirm-return').click()
  await expect(page.getByRole('status')).toContainText('退款 ¥180.00')

  await page.goto('/inventory')
  inventoryRow = page.getByRole('row').filter({ hasText: barcode })
  await expect(inventoryRow.locator('td').nth(6)).toHaveText('19')
  await inventoryRow.getByRole('button', { name: '库存调整' }).click()
  await page.getByTestId('counted-quantity').fill('18')
  await page.getByTestId('adjustment-reason').fill('破损报废')
  await page.getByTestId('confirm-adjustment').click()
  await expect(page.getByRole('row').filter({ hasText: barcode }).locator('td').nth(6)).toHaveText('18')

  await page.goto('/')
  await expect(page.getByText('今日销售额')).toBeVisible()
  await expect(page.getByText(productName)).toBeVisible()

  await page.goto('/reports')
  const rankingRow = page.getByRole('row').filter({ hasText: barcode })
  await expect(rankingRow).toContainText(skuCode)
  await expect(rankingRow.locator('td').nth(7)).toHaveText('1')
  await expect(rankingRow.locator('td').nth(8)).toContainText('180.00')

  await page.goto('/settings')
  await page.getByTestId('create-backup').click()
  await expect(page.getByRole('status')).toContainText('备份创建成功')
  await expect(page.getByRole('row').filter({ hasText: '手动备份' }).first()).toContainText('可用')
})
