import { expect, test } from '@playwright/test'

const barcode = '6700000000099'

test('扫码销售并按原单部分退货后金额、库存和成本一致', async ({ page }) => {
  await page.goto('/catalog')
  const categories = page.locator('section[aria-labelledby="categories-title"]')
  const majorForm = categories.locator('form').nth(0)
  await majorForm.getByLabel('两位编号').fill('67')
  await majorForm.getByLabel('大类名称').fill('销售验收球类')
  await majorForm.getByRole('button', { name: '新增大类' }).click()
  const minorForm = categories.locator('form').nth(1)
  await minorForm.getByLabel('所属大类').selectOption({ label: '67 销售验收球类' })
  await minorForm.getByLabel('两位编号').fill('01')
  await minorForm.getByLabel('小类名称').fill('销售验收篮球')
  await minorForm.getByRole('button', { name: '新增小类' }).click()
  const brands = page.locator('section[aria-labelledby="brands-title"]')
  const brandCount = await brands.getByLabel('品牌名称').count()
  await brands.getByLabel('品牌名称').first().fill('销售验收品牌')
  await brands.getByRole('button', { name: '新增品牌' }).click()
  await expect(brands.getByLabel('品牌名称')).toHaveCount(brandCount + 1)

  await page.goto('/inbounds')
  await page.getByTestId('barcode-input').fill(barcode)
  await page.getByTestId('scan-submit').click()
  const create = page.getByTestId('quick-create-dialog')
  await create.getByTestId('quick-sub-category').selectOption({ label: '01 销售验收篮球' })
  await create.getByTestId('quick-product-name').fill('销售验收篮球')
  await create.getByLabel('品牌').selectOption({ label: '销售验收品牌' })
  await create.getByTestId('quick-sku-code').fill('SALE-E2E-01')
  await create.getByTestId('quick-retail-price').fill('150')
  await create.getByTestId('quick-save').click()
  await page.getByTestId('pending-quantity').fill('10')
  await page.getByTestId('pending-unit-cost').fill('100')
  await page.getByTestId('add-line').click()
  await page.getByTestId('confirm-inbound').click()
  await expect(page.getByRole('status')).toContainText('入库成功')

  await page.goto('/sales')
  await page.getByTestId('barcode-input').fill(barcode)
  await page.getByTestId('scan-submit').click()
  const saleQuantity = page.getByTestId('checkout-cart').locator('input[type="number"]')
  await expect(saleQuantity).toHaveValue('1')
  await page.getByTestId('barcode-input').fill(barcode)
  await page.getByTestId('scan-submit').click()
  await expect(saleQuantity).toHaveValue('2')
  await expect(page.getByTestId('checkout-cart')).toContainText('SALE-E2E-01')
  await page.getByTestId('discount').fill('30')
  await page.getByTestId('discount').blur()
  await expect(page.getByText('¥270.00', { exact: true })).toBeVisible()
  await page.getByTestId('open-payment').click()
  await expect(page.getByTestId('payment-amount')).toHaveValue('270.00')
  await page.getByTestId('confirm-payment').click()
  const receipt = page.getByRole('dialog').filter({ hasText: '销售小票' })
  await expect(receipt).toContainText('实收：¥270.00')
  const saleNo = (await receipt.locator('dd').first().innerText()).trim()
  expect(saleNo).toMatch(/^SO-\d{8}-\d{6}$/)
  await receipt.getByRole('button', { name: '关闭' }).click()

  await page.goto('/inventory')
  let row = page.getByRole('row').filter({ hasText: barcode })
  await expect(row.locator('td').nth(6)).toHaveText('8')
  await expect(row.locator('td').nth(7)).toHaveText('100.0000')

  await page.goto('/sales/history')
  const saleRow = page.getByRole('row').filter({ hasText: saleNo })
  await saleRow.getByRole('link', { name: '查看详情' }).click()
  await page.getByRole('button', { name: '原单退货' }).click()
  const returnDialog = page.getByRole('dialog').filter({ hasText: '原单退货' })
  await returnDialog.getByTestId(/return-quantity-/).fill('1')
  await expect(returnDialog.getByTestId('refund-preview')).toContainText('135.00')
  await returnDialog.getByTestId('confirm-return').click()
  await expect(page.getByRole('status')).toContainText('退款 ¥135.00')
  await expect(page.getByText('1', { exact: true })).toBeVisible()

  await page.goto('/inventory')
  row = page.getByRole('row').filter({ hasText: barcode })
  await expect(row.locator('td').nth(6)).toHaveText('9')
  await expect(row.locator('td').nth(7)).toHaveText('100.0000')
})
