<script setup lang="ts">
import { computed, reactive, ref, watch } from 'vue'; import type { SaleLine, SaleReceipt } from '../../sales/types'; import { createReturn, returnError } from '../api'; import type { ReturnReceipt } from '../types'
const props=defineProps<{open:boolean;sale:SaleReceipt}>(); const emit=defineEmits<{close:[];success:[receipt:ReturnReceipt]}>()
const quantities=reactive<Record<string,number>>({}); const reason=ref(''); const method=ref('CASH'); const submitting=ref(false); const alert=ref('')
const availableLines=computed(()=>props.sale.lines.filter(line=>line.returnedQuantity<line.quantity))
watch(()=>props.open,(open)=>{if(open){for(const key of Object.keys(quantities))delete quantities[key];for(const line of availableLines.value)quantities[line.id]=0;alert.value=''}})
function remainingRefund(line:SaleLine){const unit=Math.round(line.actualAmount/line.quantity*100)/100;return Math.round((line.actualAmount-unit*line.returnedQuantity)*100)/100}
function lineRefund(line:SaleLine){const qty=quantities[line.id]??0;const remaining=line.quantity-line.returnedQuantity;if(qty===remaining)return remainingRefund(line);return Math.min(Math.round(line.actualAmount/line.quantity*100)/100*qty,remainingRefund(line))}
const preview=computed(()=>Math.round(availableLines.value.reduce((sum,line)=>sum+lineRefund(line),0)*100)/100)
const selected=computed(()=>availableLines.value.filter(line=>(quantities[line.id]??0)>0))
async function submit(){if(submitting.value||!selected.value.length)return;submitting.value=true;alert.value='';try{const receipt=await createReturn({originalSaleOrderId:props.sale.id,reason:reason.value,refundMethodCode:method.value,lines:selected.value.map(line=>({originalSaleLineId:line.id,quantity:quantities[line.id]!}))},crypto.randomUUID());emit('success',receipt)}catch(cause){alert.value=returnError(cause)}finally{submitting.value=false}}
</script>
<template><div v-if="open" class="overlay" role="dialog" aria-modal="true"><section><h2>原单退货</h2><p>销售单 {{ sale.orderNo }}</p><p v-if="!availableLines.length">该销售单已无可退商品。</p>
  <table v-else><thead><tr><th>SKU</th><th>已售/已退</th><th>本次退货</th><th>预计退款</th></tr></thead><tbody><tr v-for="line in availableLines" :key="line.id"><td>{{line.skuCode}}</td><td>{{line.quantity}} / {{line.returnedQuantity}}</td><td><input v-model.number="quantities[line.id]" :data-testid="`return-quantity-${line.id}`" type="number" min="0" :max="line.quantity-line.returnedQuantity" step="1"></td><td>¥{{lineRefund(line).toFixed(2)}}</td></tr></tbody></table>
  <div class="fields"><label>退款方式<select v-model="method"><option value="CASH">现金</option><option value="WECHAT">微信</option><option value="ALIPAY">支付宝</option><option value="BANK_CARD">银行卡</option></select></label><label>原因<input v-model="reason" maxlength="500"></label></div>
  <p data-testid="refund-preview" class="total">预计退款 ¥{{preview.toFixed(2)}}</p><p v-if="alert" role="alert" class="error">{{alert}}</p><footer><button type="button" @click="emit('close')">取消</button><button data-testid="confirm-return" type="button" :disabled="!selected.length||submitting" @click="submit">{{submitting?'提交中…':'确认退货'}}</button></footer>
</section></div></template>
<style scoped>.overlay{position:fixed;inset:0;background:#0f172a88;display:grid;place-items:center;z-index:25}.overlay section{background:#fff;border-radius:.8rem;padding:1.4rem;width:min(50rem,94vw)}table{width:100%;border-collapse:collapse}th,td{padding:.65rem;border-bottom:1px solid #e2e8f0;text-align:left}input,select{padding:.55rem}.fields{display:flex;gap:1rem;margin-top:1rem}.fields label{display:grid;gap:.3rem;flex:1}.total{text-align:right;font-size:1.3rem;font-weight:800}.error{color:#b91c1c}footer{display:flex;justify-content:flex-end;gap:.6rem}</style>
